// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsK_6I1AuCQ27-RXDy7l3h1jP8OZ2UqG8',
    appId: '1:153478223116:web:daf1e911d2c005c955a529',
    messagingSenderId: '153478223116',
    projectId: 'home-service-booking-app-89796',
    authDomain: 'home-service-booking-app-89796.firebaseapp.com',
    storageBucket: 'home-service-booking-app-89796.firebasestorage.app',
    measurementId: 'G-RJXSWSL9HY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClVZiw4DonvvS8PsaV7BVr0RIUuxw4evA',
    appId: '1:153478223116:android:c9acb53c62c33a4555a529',
    messagingSenderId: '153478223116',
    projectId: 'home-service-booking-app-89796',
    storageBucket: 'home-service-booking-app-89796.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiiacXH3_LHNB7huZPnsC4T_gXGxh95mc',
    appId: '1:153478223116:ios:910f083af7b7ca1155a529',
    messagingSenderId: '153478223116',
    projectId: 'home-service-booking-app-89796',
    storageBucket: 'home-service-booking-app-89796.firebasestorage.app',
    iosBundleId: 'com.example.homeServiceBookinApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiiacXH3_LHNB7huZPnsC4T_gXGxh95mc',
    appId: '1:153478223116:ios:910f083af7b7ca1155a529',
    messagingSenderId: '153478223116',
    projectId: 'home-service-booking-app-89796',
    storageBucket: 'home-service-booking-app-89796.firebasestorage.app',
    iosBundleId: 'com.example.homeServiceBookinApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsK_6I1AuCQ27-RXDy7l3h1jP8OZ2UqG8',
    appId: '1:153478223116:web:081cb1a279afe63955a529',
    messagingSenderId: '153478223116',
    projectId: 'home-service-booking-app-89796',
    authDomain: 'home-service-booking-app-89796.firebaseapp.com',
    storageBucket: 'home-service-booking-app-89796.firebasestorage.app',
    measurementId: 'G-XJPCJN4C7T',
  );
}
